version: '3.3'

services:
  jira:
    depends_on:
      - jiraconfldb
    build: 
      context: ./jira
      args:
        - JIRA_VERSION=7.12.1
        - JDBC_DL_PATH=https://jdbc.postgresql.org/download/
        - JDBC_DRIVER=postgresql-42.2.5.jar
    networks:
      - jiraconflnet
    volumes:
      - /data/jiradata/var:/var/atlassian/jira
      - /data/jiradata/optlogs:/opt/atlassian/jira/logs
    ports:
      - "8080:8080"
    environment:
      - JIRA_DATABASE_URL=postgresql://jira@jiraconfldb/jiradb
      - JIRA_DB_PASSWORD=jira2018
      - SETENV_JVM_MINIMUM_MEMORY=256m
      - SETENV_JVM_MAXIMUM_MEMORY=1g
      - JIRA_PROXY_NAME=
      - JIRA_PROXY_PORT=
      - JIRA_PROXY_SCHEME=
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"

  confluence:
    depends_on:
      - jiraconfldb
    build: 
      context: ./confluence
      args:
        - CONF_VERSION=6.11.0
        - JDBC_DL_PATH=https://jdbc.postgresql.org/download/
        - JDBC_DRIVER=postgresql-42.2.5.jar 
    networks:
      - jiraconflnet
    volumes:
      - /data/confluencedata/varlogs:/var/atlassian/confluence/logs
      - /data/confluencedata/optlogs:/opt/atlassian/confluence/logs
    ports:
      - "8090:8090"
      - "8091:8091"
    environment:
      - JVM_MINIMUM_MEMORY=1024m
      - JVM_MAXIMUM_MEMORY=1024m
      - CATALINA_CONNECTOR_PROXYNAME=
      - CATALINA_CONNECTOR_PROXYPORT=
      - CATALINA_CONNECTOR_SCHEME=
      - CATALINA_CONNECTOR_SECURE=
      - JVM_SUPPORT_RECOMMENDED_ARGS=
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"


  jiraconfldb:
    build:
      context: ./postgresql
      args:
        - CONFLUENCE_DB_USER=confluence
        - CONFLUENCE_DB_PASSWORD=confl2018
        - CONFLUENCE_DBNAME=confluencedb
        - JIRA_DB_USER=jira
        - JIRA_DB_PASSWORD=jira2018
        - JIRA_DBNAME=jiradb
    networks:
      - jiraconflnet
    volumes:
      - /data/postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER= 
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "50"


networks:
  jiraconflnet:
    driver: bridge

